export const newAllCategoriesList : Set<string> = new Set([
  "All Categories", "Entertainment", "Groceries", "Eating Out", "Shopping", "Medical", "Personal Care", "Loans",
  "General Expenses", "Transportation", "Vacation", "Rent & Utilities", "Income", "Transfer", "Fees & Charges",
]);

export const isNonEssentialSpend : Set<string> = new Set([
  "All Categories", "Entertainment", "Groceries", "Eating Out", "Shopping", "Medical", "Personal Care",
  "General Expenses", "Transportation", "Vacation", "Rent & Utilities",
]);

export const isEssentialSpend : Set<string> = new Set([
  "All Categories", "Income", "Loans", "Transfer", "Fees & Charges",
]);

export const newCategoriesSpendMap : Map<any, any> = new Map<any, any>([
  ["RENT_AND_UTILITIES_GAS_AND_ELECTRICITY", "Rent & Utilities"],
  ["RENT_AND_UTILITIES_INTERNET_AND_CABLE", "Rent & Utilities"],
  ["RENT_AND_UTILITIES_RENT", "Rent & Utilities"],
  ["RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT", "Rent & Utilities"],
  ["RENT_AND_UTILITIES_TELEPHONE", "Rent & Utilities"],
  ["RENT_AND_UTILITIES_WATER", "Rent & Utilities"],
  ["RENT_AND_UTILITIES_OTHER_UTILITIES", "Rent & Utilities"],
  ["TRAVEL_OTHER_TRAVEL", "Vacation"],
  ["TRAVEL_RENTAL_CARS", "Vacation"],
  ["TRAVEL_LODGING", "Vacation"],
  ["TRAVEL_FLIGHTS", "Vacation"],
  ["TRANSPORTATION_OTHER_TRANSPORTATION", "Transportation"],
  ["TRANSPORTATION_TOLLS", "Transportation"],
  ["TRANSPORTATION_TAXIS_AND_RIDE_SHARES", "Transportation"],
  ["TRANSPORTATION_PUBLIC_TRANSIT", "Transportation"],
  ["TRANSPORTATION_PARKING", "Transportation"],
  ["TRANSPORTATION_GAS", "Transportation"],
  ["TRANSPORTATION_BIKES_AND_SCOOTERS", "Transportation"],
  ["GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT", "General Expenses"],
  ["GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT", "General Expenses"],
  ["GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES", "General Expenses"],
  ["GOVERNMENT_AND_NON_PROFIT_DONATIONS", "General Expenses"],
  ["GENERAL_SERVICES_OTHER_GENERAL_SERVICES", "General Expenses"],
  ["GENERAL_SERVICES_STORAGE", "General Expenses"],
  ["GENERAL_SERVICES_POSTAGE_AND_SHIPPING", "General Expenses"],
  ["GENERAL_SERVICES_INSURANCE", "General Expenses"],
  ["GENERAL_SERVICES_EDUCATION", "General Expenses"],
  ["GENERAL_SERVICES_CONSULTING_AND_LEGAL", "General Expenses"],
  ["GENERAL_SERVICES_CHILDCARE", "General Expenses"],
  ["GENERAL_SERVICES_AUTOMOTIVE", "General Expenses"],
  ["GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING", "General Expenses"],
  ["PERSONAL_CARE_OTHER_PERSONAL_CARE", "Personal Care"],
  ["PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING", "Personal Care"],
  ["PERSONAL_CARE_HAIR_AND_BEAUTY", "Personal Care"],
  ["PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS", "Personal Care"],
  ["MEDICAL_OTHER_MEDICAL", "Medical"],
  ["MEDICAL_VETERINARY_SERVICES", "Medical"],
  ["MEDICAL_PRIMARY_CARE", "Medical"],
  ["MEDICAL_PHARMACIES_AND_SUPPLEMENTS", "Shopping"],
  ["MEDICAL_NURSING_CARE", "Medical"],
  ["MEDICAL_EYE_CARE", "Medical"],
  ["MEDICAL_DENTAL_CARE", "Medical"],
  ["HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT", "Shopping"],
  ["HOME_IMPROVEMENT_SECURITY", "Shopping"],
  ["HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE", "Shopping"],
  ["HOME_IMPROVEMENT_HARDWARE", "Shopping"],
  ["HOME_IMPROVEMENT_FURNITURE", "Shopping"],
  ["GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE", "Shopping"],
  ["GENERAL_MERCHANDISE_TOBACCO_AND_VAPE", "Shopping"],
  ["GENERAL_MERCHANDISE_SUPERSTORES", "Shopping"],
  ["GENERAL_MERCHANDISE_SPORTING_GOODS", "Shopping"],
  ["GENERAL_MERCHANDISE_PET_SUPPLIES", "Shopping"],
  ["GENERAL_MERCHANDISE_ONLINE_MARKETPLACES", "Shopping"],
  ["GENERAL_MERCHANDISE_OFFICE_SUPPLIES", "Shopping"],
  ["GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES", "Shopping"],
  ["GENERAL_MERCHANDISE_ELECTRONICS", "Shopping"],
  ["GENERAL_MERCHANDISE_DISCOUNT_STORES", "Shopping"],
  ["GENERAL_MERCHANDISE_DEPARTMENT_STORES", "Shopping"],
  ["GENERAL_MERCHANDISE_CONVENIENCE_STORES", "Shopping"],
  ["GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES", "Shopping"],
  ["GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS", "Shopping"],
  ["FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK", "Eating Out"],
  ["FOOD_AND_DRINK_VENDING_MACHINES", "Eating Out"],
  ["FOOD_AND_DRINK_RESTAURANT", "Eating Out"],
  ["FOOD_AND_DRINK_GROCERIES", "Groceries"],
  ["FOOD_AND_DRINK_FAST_FOOD", "Eating Out"],
  ["FOOD_AND_DRINK_COFFEE", "Eating Out"],
  ["FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR", "Eating Out"],
  ["ENTERTAINMENT_OTHER_ENTERTAINMENT", "Entertainment"],
  ["ENTERTAINMENT_VIDEO_GAMES", "Entertainment"],
  ["ENTERTAINMENT_TV_AND_MOVIES", "Entertainment"],
  ["ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS", "Entertainment"],
  ["ENTERTAINMENT_MUSIC_AND_AUDIO", "Entertainment"],
  ["ENTERTAINMENT_CASINOS_AND_GAMBLING", "Entertainment"],
  ["BANK_FEES_OTHER_BANK_FEES", "Fees & Charges"],
  ["BANK_FEES_OVERDRAFT_FEES", "Fees & Charges"],
  ["BANK_FEES_INTEREST_CHARGE", "Fees & Charges"],
  ["BANK_FEES_INSUFFICIENT_FUNDS", "Fees & Charges"],
  ["BANK_FEES_FOREIGN_TRANSACTION_FEES", "Fees & Charges"],
  ["BANK_FEES_ATM_FEES", "Fees & Charges"],
  ["LOAN_PAYMENTS_OTHER_PAYMENT", "Loans"],
  ["LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT", "Loans"],
  ["LOAN_PAYMENTS_MORTGAGE_PAYMENT", "Loans"],
  ["LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT", "Loans"],
  ["LOAN_PAYMENTS_CREDIT_CARD_PAYMENT", "Transfer"],
  ["LOAN_PAYMENTS_CAR_PAYMENT", "Loans"],
  ["TRANSFER_OUT_OTHER_TRANSFER_OUT", "Transfer"],
  ["TRANSFER_OUT_ACCOUNT_TRANSFER", "Transfer"],
  ["TRANSFER_OUT_WITHDRAWAL", "Transfer"],
  ["TRANSFER_OUT_SAVINGS", "Transfer"],
  ["TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS", "Transfer"],
  ["TRANSFER_IN_OTHER_TRANSFER_IN", "Transfer"],
  ["TRANSFER_IN_ACCOUNT_TRANSFER", "Transfer"],
  ["TRANSFER_IN_SAVINGS", "Transfer"],
  ["TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS", "Transfer"],
  ["TRANSFER_IN_DEPOSIT", "Transfer"],
  ["TRANSFER_IN_CASH_ADVANCES_AND_LOANS", "Transfer"],
  ["INCOME_OTHER_INCOME", "Income"],
  ["INCOME_WAGES", "Income"],
  ["INCOME_UNEMPLOYMENT", "Income"],
  ["INCOME_TAX_REFUND", "Income"],
  ["INCOME_RETIREMENT_PENSION", "Income"],
  ["INCOME_INTEREST_EARNED", "Income"],
  ["INCOME_DIVIDENDS", "Income"],
]);